spring:
  datasource:
    url: jdbc:mysql://35.226.151.250:3306/coffee_app_db
    password: cofeeapp@123
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true